import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import CategoyRegions from './subSchema/enums/Categoryregion.enum';
import { HydratedDocument } from 'mongoose';
import { Translations } from './subSchema/index';

export type CategoryDocument = HydratedDocument<Category>;

@Schema()
export class Category {
  @Prop({ type: String, required: true, title: 'Name' })
  public name: string;

  @Prop({
    type: String,
    readonly: true,
    title: 'Nice Name',
    description: 'Autogenerated identifier',
  })
  public niceName: string;

  @Prop({ type: String, format: 'mycook-image' })
  public image: string;

  @Prop({ type: Boolean, title: 'Visibility', default: false })
  public visibility: boolean;

  @Prop({
    type: String,
    required: true,
    enum: CategoyRegions,
    title: 'Region',
  })
  public region: string;

  @Prop({
    type: String,
    format: 'html',
  })
  public landingText: string;

  @Prop([
    {
      type: String,
      title: 'Synonyms',
    },
  ])
  public synonyms: string[];

  @Prop(Translations)
  public translations: Translations;
}

export const categorySchema = SchemaFactory.createForClass(Category);
