import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import CategoyRegions from './subSchema/enums/Categoryregion.enum';
import { Translations } from './subSchema/index';

export type CategoryDocument = HydratedDocument<Category>;

@Schema()
export class Category {
  @Prop({ type: String, required: true, title: 'Name' })
  name: String;

  @Prop({
    type: String,
    readonly: true,
    title: 'Nice Name',
    description: 'Autogenerated identifier',
  })
  niceName: String;

  @Prop({ type: String, format: 'mycook-image' })
  image: String;

  @Prop({ type: Boolean, title: 'Visibility', default: false })
  visibility: Boolean;

  @Prop({
    type: String,
    required: true,
    enum: CategoyRegions,
    title: 'Region',
  })
  region: String;

  @Prop({
    type: String,
    format: 'html',
  })
  landingText: String;

  @Prop([
    {
      type: String,
      title: 'Synonyms',
    },
  ])
  synonyms: String[];

  @Prop(Translations)
  translations: Translations;
}

export const CategorySchema = SchemaFactory.createForClass(Category);
